language: rust

cache: cargo

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      os: linux
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-gnu
      os: linux
      rust: beta
    - env: TARGET=x86_64-unknown-linux-gnu
      os: linux
      rust: stable

install:
  - rustup self update
  - rustup target add $TARGET; true

script:
  - cargo build --all --target $TARGET --verbose
  - cargo test --all --target $TARGET --verbose

after_success:
  - test "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false"
    && cargo publish --token ${CRATESIO_TOKEN}
